title: Richard Saunders, Product owner and designer
email: mail@rdsaunders.co.uk
description: "The personal site of Richard Saunders, product owner of @contensis and designer based in Newport, South Wales"
url: "https://www.rdsaunders.co.uk"
baseurl: ""
author: Richard Saunders
lang: en_GB

# Social Networks
twitter_username: rdsaunders
github_username:  rdsaunders
dribbble_username: rdsaunders
instagram_username: richardsaunders

# Theme / Manifest
theme_color: "#307fe2"

# Default URL Structure
permalink: /:categories/:year/:month/:day/:title

# GitHub
github:
  repo: "rdsaunders/rdsaunders"
  branch: master


# Build settings
markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag

# File/folder exclusions
exclude: [node_modules, _importers, README.md]

# Site collections
collections:
  links:
    output: true
    permalink: /bookmarks/:year/:month/:title
  notes:
    output: true
    permalink: /notes/:year:month:day:hour:minute:second
  checkins:
    output: true
    permalink: /checkins/:year:month:day:hour:minute:second
  tweets:
    output: true
    permalink: /twitter/:title
  talks:
    output: true
  photos:
    output: true
    permalink: /photos/:year/:month/:day/:title

# Post layout defaults
defaults:
  - scope:
      type: posts
    values:
      layout: post
      is_post: true
  - scope:
      type: notes
    values:
      layout: note
  - scope:
      type: checkins
    values:
      layout: checkin
  - scope:
      type: tweets
    values:
      layout: tweet
  - scope:
      type: talks
    values:
      layout: talk
  - scope:
      type: links
    values:
      layout: link
  - scope:
      type: photos
    values:
      layout: photo




pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 8

  # The permalink structure for the paginated pages (this can be any level deep)
  #permalink: '/page:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  permalink: '/page/:num'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

cloudinary_url: https://res.cloudinary.com/rdsaunders/

mapbox: pk.eyJ1IjoicmRzYXVuZGVycyIsImEiOiJjazNlaGQ3YXoxMDJpM251aTJzemx5ZjRrIn0.MiRvAifw2AcQ6WP2vWCaKQ

# Webmentions config

webmentions:
  username: www.rdsaunders.co.uk
  cache_folder: .cache
  cache_bad_uris_for: 5
  templates:
    likes: _includes/webmentions/likes.html
    reposts: _includes/webmentions/reposts.html
    webmentions: _includes/webmentions/webmentions.html
