# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Richard Saunders, Product owner and UX Designer
email: mail@rdsaunders.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Product owner of @contensis
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rdsaunders.co.uk" # the base hostname & protocol for your site, e.g. http://example.com

# Social Networks
twitter_username: rdsaunders
github_username:  rdsaunders
dribbble_username: rdsaunders
instagram_username: richardsaunders


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  notes:
    output: true
  talks:
    output: true

# Post layout defaults
defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: talks
    values:
      layout: talk

paginate: 20
paginate_path: "/page:num/"