---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _photos
  label: Photos
  create: documents
  match: "**/*"
  templates:
  - photos
- type: directory
  path: _photosets
  label: Photosets
  create: all
  match: "**/*"
- type: directory
  path: _talks
  label: Talks
  create: all
  match: "**/*"
- type: directory
  path: _notes
  label: Notes
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: ''
public_path: https://res.cloudinary.com/rdsaunders/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
