---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Blog
  create: documents
  templates:
  - posts
- type: directory
  path: _links
  label: Bookmarks
  create: documents
  match: "**/*"
  templates:
  - link
- type: directory
  path: _talks
  label: Talks
  create: all
  match: "**/*"
- type: heading
  label: Photography
- type: directory
  path: _photos
  label: Photos
  create: documents
  match: "**/*"
  templates:
  - photos
- type: directory
  path: _photosets
  label: Photosets
  create: all
  match: "**/*"
- type: heading
  label: Metadata
- type: document
  path: _data/categories.yml
  label: Categories
- type: document
  path: _data/tags.yml
  label: Tags
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":year:/:month:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
